### ISSUE TITLE
Save game

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#116]
## Description
The game must save when the player reaches new parts of the cases, so they can resume after exiting.
It's probably best to avoid PlayerPrefs.
DO NOT use C#'s BinaryFormatter.
Maybe save data to AppData, or documents? It must work independent of platform. Discuss with programming team.

## Acceptance Criteria
This story will be finished when a system is in place that write data to a file, then load that data when the game opens.

**Comment by ViMaSter** [comment]
I thinl a good potential approach would be using Unity's [PlayerPrefs](https://docs.unity3d.com/ScriptReference/PlayerPrefs.html):
> `PlayerPrefs` is a class that stores Player preferences between game sessions.

and

> Unity stores `PlayerPrefs` data differently based on which operating system the application runs on. In the file paths given on this page, the company name and product name are the names you set in Unity’s Player Settings.

As `It can store string, float and integer values into the user’s platform registry.` only, we could simply create a `struct` or `class`, which contains properties for all the things we want to store and convert that from and to `JSON` to save and load it as a `string`.

We should also support different "versions" of settings. If later on we decide to add new settings, remove unused ones or move them to another part of the object, we shouldn't force users to re-play the game, just because we can no longer parse their save.

---

I've built a rough implementation as a starting point:
- Note that this is pseudo-code and not actually ran and tested
- That said: It seems pretty testable and saving, loading and upgrading are all areas where things can go wrong pretty badly
- `GameSettings.Data` is the passive data object with everything we want to store
- `GameSettings.Helper.HasExistingPlayerPrefs()` can check if there's already stored data present (useful to warn users about overwriting their existing save file and checking if we can even load any data at startup)
- `GameSettings.Helper.LoadFromPlayerPrefs()` loads a `GameSettings.Data` object via `PlayerPrefs`
  - it also upgrades it to the latest version, should stored data be outdated
  - in my example, version 1 stored the resolution as `float Width, Height`, but version 2 stores it as `Vector2 Resolution` (see `GameSettings.Helper.UpgradeGameSettings()`)
- `GameSettings.Helper.SaveToPlayerPrefs()` takes care of serializing a `GameSettings.Data` instance and storing it inside `PlayerPrefs`
```cs
namespace GameSettings
{
    /// <summary>
    /// Passive data structure of all available settings of the game
    /// that are stored across sessions
    /// </summary>
    public final class Data
    {
        public final class AudioSettings
        {
            public float MasterVolume { get; set; }
            public float SFXVolume { get; set; }
            public float MusicVolume { get; set; }
            public float VoiceVolume { get; set; }
        }
        public final class VideoSettings
        {
            public Vector2 Resolution { get; set; }
            public FullScreenMode FullScreenMode { get; set; }
        }

        // this is usually a good practice to have
        // if we - at a later point - decide to make changes to this class
        // we can import old playerprefs and convert them
        public int Version = 0;

        public AudioSettings AudioSettings;
        public VideoSettings VideoSettings;
    }

    /// <summary>
    /// Methods to use, when attempting to modify or read <see cref="GameSettings.Data"/>
    /// </summary>
    public static class Helper
    {
        public bool HasExistingPlayerPrefs()
        {
            return PlayerPrefs.HasKey("GameSettings");
        }

        /// <summary>
        /// If attempting to LoadFromPlayerPrefs() encounters data which has a lower <see cref="GameSettings.Data"/>
        /// than this game would produce, we need to manually migrate this object from the old format to the current one
        /// </summary>
        /// <param name="outdatedVersion">The version the <see cref="outdatedSettingsJSON"/> is based on</param>
        /// <param name="outdatedSettingsJSON">Dynamic object representing the outdated JSON-blob of the loaded settings</param>
        private void UpgradeGameSettings(int outdatedVersion, dynamic outdatedSettingsJSON, ref GameSettings upgradedGameSettings)
        {
            // if we receive a GameSettings object with an outdated `Version`,
            // we have to manually parse it into the current format based on it's version number
            switch (outdatedVersion)
            {
                case 1:
                    // Let's say there's a change from v1 to v2
                    // - Screen resolution is stored in Vector2 instead of two floats
                    upgradedGameSettings.VideoSettings.Resolution = new Vector2(outdatedSettingsJSON.VideoSettings.Width, outdatedSettingsJSON.VideoSettings.Height);
                    break;
                case 2:
                    break;
                case 3:
                    break;
                // case ...
            }
        }
        
        public GameSettings LoadFromPlayerPrefs()
        {
            Debug.Assert(PlayerPrefs.HasKey("GameSettings"), "No previously saved game settings available to load - call HasExistingPlayerPrefs() first, to make sure there's settings available to load");

            // store this, as loading PlayerPrefs can be slow on certain platforms
            string storedSettings = PlayerPrefs.GetString("GameSettings");

            GameSettings storedGameSettings = JsonConvert.DeserializeObject(storedSettings);
            GameSettings newGameSettings = new GameSettings();

            // assert, that stored game settings are never newer than this version of the game supports
            Debug.Assert(newGameSettings.version >= storedGameSettings.version, "The game settings stored on this machine are newer than this version of the game supports - make sure you're running the latest version of the game");

            // if stored GameSettings are older than this game supports,
            // we need to upgrade them into the current format
            if (storedGameSettings.version != newGameSettings.version)
            {
                GameSettings upgradedGameSettings = UpgradeGameSettings(storedGameSettings.version, JsonConvert.DeserializeObject<dynamic>(storedSettings), ref storedGameSettings);
                SaveToPlayerPrefs(storedGameSettings);
                return upgradedGameSettings;
            }
            
            // otherwise simply parse the stored GameSettings JSON blob
            return JsonConvert.DeserializeObject(storedSettings);
        }
        
        public GameSettings SaveToPlayerPrefs(GameSettings gameSettings)
        {
            return PlayerPrefs.SetString("GameSettings", JsonConvert.SerializeObject(this));
        }
    }
}
```

**Comment by ViMaSter** [comment]
@PhoebeMitchell I suppose `DO NOT use C#'s BinaryFormatter.` is to prevent issues with endianness? (And if not, could you elaborate? Just curious what I'm missing on, almost always relied on existing solutions for serialization.👀)

**Comment by PhoebeMitchell** [comment]
@ViMaSter From https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter?view=net-6.0
"BinaryFormatter is insecure and can't be made secure. For more information, see the BinaryFormatter security guide."
I mentioned it because there are a lot of save/load tutorials using it still.

Admittedly unsure what the risk is for an application such as ours, but BinaryReader and BinaryWriter exist so might as well use them instead if we wanted to go down that route.
