### ISSUE TITLE
[BUG] Doc Generator Generates the wrong "Scenes" constants

### ISSUE THREAD

**Issue by notexplosive** [Studio-Lovelies/GG-JointJustice-Unity#193]
## Describe the bug

In the generated docs we list the scenes in `constants.md`, it looks like this.
![image](https://user-images.githubusercontent.com/6920005/154185589-7fb9611d-3599-4207-9306-5d56a64de788.png)

This is.... not right? It should list all possible BGScenes...? Right?

**Comment by ViMaSter** [comment]
I actually think this is okay the way it is: These docs are intended for writers and designers, so the test scenes we only use for automated or manual tests not being listed here makes sense to me.

As for the underlying cause: [The doc gen is working as intended, as it only looks for `*.unity`-files **directly** in the folder specified here](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/develop/unity-ggjj/Assets/Scripts/TextDecoder/ActionDecoder.cs#L375). If we want it be recursive, we'd have to extend the generator to support something like `Assets/Scenes/**.unity` to also include subdirectories.

That aside, I'm sure this will automatically resolve itself, as soon as #173 is implemented anyway: Once the resources not used by the final game's executable are inside a separate Assembly (and thereby other folders), the docs will only contain the scenes we can actually use in the final game. And since we want to keep the main narrative inside one scene, I'm not sure if we'll need subfolders inside the `Scenes`-folder in the near future.

**Comment by PhoebeMitchell** [comment]
> I actually think this is okay the way it is: These docs are intended for writers and designers, so the test scenes we only use for automated or manual tests not being listed here makes sense to me.

The issue is it should be showing BGScenes, as these are the "scenes" that writers use when using the &SCENE action (TMPHCourt, TMPHLobby, etc). The writers don't need to know what the Unity scenes are so they don't need to be listed.
