### ISSUE TITLE
&LOAD_SCENE action

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#234]
## Description
An action needs to be added to ~start the credits.~ load other scenes, for example the credits scene.
It should be something like ~`&CREDITS`~ `&LOAD_SCENE:SceneName` where `SceneName` is the name of the scene to load e.g., `Credits`

## Acceptance Criteria
Scenes can be loaded via an action.

**Comment by ViMaSter** [comment]
Could we reuse [the `&LOAD_SCENE` / `&SCENE` action](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/discussions/170#:~:text=I.%206.%3A%20the%20final%20ink%20script%20uses%20the%20%26SCENE%3ACredits%20line%20to%20abort%20that%20loop%20and%20exit%20the%20Game%20scene%20before%20the%20NarrativeScriptPlaylist%20runs%20out%20of%20scripts%20to%20parse) for this or is there a need for a credits-specific action?  
It's definitely a good item to keep track off, just wondering if we'd save time if we define the scene name as a parameter, so if we have things like minigames later down the line, we can switch to them with that same command.

**Comment by PhoebeMitchell** [comment]
There currently isn't a LOAD_SCENE action but I agree that would be a good idea. Then as you say LOAD_SCENE could load the credits, or minigames, etc.

LOAD_SCRIPT doesn't reload the game scene, just sets up the next narrative script, so I think a separate LOAD_SCENE action would be better.

SCENE just enables and disables BGScenes and I think it would be better to make the credits its own scene within Unity.

**Comment by ViMaSter** [comment]
> There currently isn't a LOAD_SCENE action but I agree that would be a good idea. Then as you say LOAD_SCENE could load the credits, or minigames, etc.

Exactly! Basically for anything, where we exit the narrative loop.

> LOAD_SCRIPT doesn't reload the game scene, just sets up the next narrative script, so I think a separate LOAD_SCENE action would be better.

Absolutely makes sense; the term "reuse" was a bit irritating, I admit. I actually was referring to creating a new `LOAD_SCENE` action, referring to loading Unity Scenes, (rather than the current narrative scenes).

> SCENE just enables and disables BGScenes and I think it would be better to make the credits its own scene within Unity.

Maybe similarly to the overlap with the term "script" (referring to either an Ink Script or C# Script), we could come up with something to use instead, that doesn't clash with existing Unity vocabulary? That way we wouldn't have to qualify them as Ink Scenes and Unity Scenes.  
I could see something like "stage", "act"  or "location" working for scene. "Screenplay" could be an alternative for Ink scripts.

**Comment by PhoebeMitchell** [comment]
Updated the issue to request a LOAD_SCENE action.

Opened a discussion for naming of scenes here:
https://github.com/Studio-Lovelies/GG-JointJustice-Unity/discussions/236
