### ISSUE TITLE
[BUG] The output of automated builds is at a wonky resolution (and probably isn't playable)

### ISSUE THREAD

**Issue by notexplosive** [Studio-Lovelies/GG-JointJustice-Unity#239]
## Describe the bug

We have automated builds on every PR which is great! But if I go download the latest binaries and try to run them... it's not playable.

## Steps To Reproduce

Download the latest build in the releases section (I chose windows x64). Try to run it.
![image](https://user-images.githubusercontent.com/6920005/160520910-3a9b0c40-35ff-4267-b96e-e648efd0a6f3.png)

## Expected behavior

I should be dropped into some kind of playable scene at a playable resolution.

## Screenshots

Here's the tiny window I see when I try to run the game. I think I see the edge of a dialogue box.
![image](https://user-images.githubusercontent.com/6920005/160521078-59fbe6d8-f727-4fcd-911c-f3a4177e1de1.png)

## Additional context

This might be a "wyatt has a giant monitor" problem? I'm on a 4K display so maybe that effects my starting resolution? I don't think so though.

**Comment by notexplosive** [comment]
Tagging as `no code` because I'm pretty sure this is just Unity UI fiddling.

**Comment by ViMaSter** [comment]
This might have something to do with it... : D
![image](https://user-images.githubusercontent.com/1689033/160572135-86a2ac42-e0f6-4112-8907-c7c7723c2c2e.png)
These builds haven't been updated since we decided that Releases should only be used for things that also land on itch.io. I've just never gotten around to deleting these development builds.  

If you want me to, I can delete all the tags (and thereby remove all Releases on GitHub).

**Small note:** Releases and build artifacts on GitHub are two separate things.  
[Releases](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/releases) are pinned and never deleted.  
[Build artifacts](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/actions/runs/2047863831#:~:text=Show%20more-,Artifacts,-Produced%20during%20runtime) are [deleted after a maximum of 90 days](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#:~:text=By%20default%2C%20the,or%2090%20days.). That said, I can't really see, why would want to keep build artifacts older than 90 days, as we can always re-run Actions for a specific commit if we really wanted to restore them.

---

Moving past that, this is what the `x64 Windows` build of both 15a449d56801f7db26457fdd3c00556228ec04cd (latest `develop` commit atm.) and 72421d897ed4331796f033e7344d38eebfaf8344 (release tag 291) look like in front of my browser with this task open:
![image](https://user-images.githubusercontent.com/1689033/160572765-8e5e47d7-239a-4fc8-9629-c1d89146fc3a.png)

The game measures exactly 1280x768 pixels, which is a bit odd, given [1280x720 is the default in the ProjectSettings](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/15a449d56801f7db26457fdd3c00556228ec04cd/unity-ggjj/ProjectSettings/ProjectSettings.asset#L47-L50).
My Windows display settings for reference:
![image](https://user-images.githubusercontent.com/1689033/160569879-2f85b085-2b7e-4d52-9c50-997d9ffc456e.png)

So it seems like it 
  - doesn't respect the [ProjectSettings](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/15a449d56801f7db26457fdd3c00556228ec04cd/unity-ggjj/ProjectSettings/ProjectSettings.asset#L47-L50)
  - works differently on your machine than on mine (feel free to give [the latest `develop` build](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/actions/runs/2047863831#:~:text=87.2%20MB-,Windows%2Dx64%2Dv887,-282%20MB) a shot too, maybe it works there?)
  - has a different aspect ratio on both of our machines
  - ignores window scaling (with 200% UI scaling, the window should be 2560x1536, rather than 1280x720)
