### ISSUE TITLE
[BUG] Controls bar in pause menu shows wrong controls

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#258]
## Describe the bug
Currently the controls bar in the pause menu shows the controls for the evidence menu.

## Steps To Reproduce
Start the game. Open the pause menu.

## Expected behavior
The controls bar should look like how it does in Lua build.
<img width="943" alt="Screenshot 2022-04-12 at 00 12 04" src="https://user-images.githubusercontent.com/67964179/162848000-c1be1eec-3d0a-44bf-81df-dadfdb7e41c2.png">

**Comment by ViMaSter** [comment]
Rather than just showing the close button mapping, I list both the select and close key in #337 :
![](https://user-images.githubusercontent.com/1689033/218284106-25263ed1-ad4f-4d19-8646-fa0f11ad54de.png)

Let me know if that works for you from a design perspective or if you want me to change the PR.
