### ISSUE TITLE
Game should pause when pause menu is open

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#263]
## Description
Currently the game just continues player when the pause menu is open. The game should pause.

## Acceptance Criteria

This story will be finished when the game pauses when the pause menu is open.

**Comment by ViMaSter** [comment]
Reading this, this _might_ be worth splitting up into multiple items for each aspect of the game pausing it has an impact on?
Things that came to my mind thinking about it a bit (including things we might already have):
- mouse, keyboard and gamepad input only affects the pause menu
- when pausing mid-dialogue, letters should stop appearing (and thereby also play no sound) until the game is resumed
- audio / music
  - if I can make a "things no one cares about but I find super neat when I notice it" request: instead of stopping the music or just lowering it, could we apply [a low-pass filter (0:00 - 0:10)](https://www.youtube.com/watch?v=EXeOKt5QvdI)? (or something else that's not just a fade? pretty sure the audio peeps would have fun ideas)

**Comment by PhoebeMitchell** [comment]
> Reading this, this _might_ be worth splitting up into multiple items for each aspect of the game pausing it has an impact on? Things that came to my mind thinking about it a bit (including things we might already have):
> 
> * mouse, keyboard and gamepad input only affects the pause menu
> * when pausing mid-dialogue, letters should stop appearing (and thereby also play no sound) until the game is resumed
> * audio / music
>   
>   * if I can make a "things no one cares about but I find super neat when I notice it" request: instead of stopping the music or just lowering it, could we apply [a low-pass filter (0:00 - 0:10)](https://www.youtube.com/watch?v=EXeOKt5QvdI)? (or something else that's not just a fade? pretty sure the audio peeps would have fun ideas)

I'm assuming/hoping pausing can be handled by just setting timescale to 0. Unsure how that affects buttons, and music. Input should already be handled in the current build.
