### ISSUE TITLE
Background-Scene Switching

### ISSUE THREAD

**Issue by JuiceGrape** [Studio-Lovelies/GG-JointJustice-Unity#29]
## Description

As the game has multiple background scenes (bg-scenes), we want to be able to switch between them. When the SCENE command is triggered from the dialogue script, the current bg-scene should be disabled, and the new bg-scene should be enabled.

## Dev Guide

- A bg-scene should consists of three parts: Background, actor, foreground. 
- The background is a still image of the background, and is on render layer 0
- The Actor is an object that the scene manager can always reference to and expose to other scripts which contains a sprite renderer and an animator. It is on render layer 1.
- The foreground is a still or animated image that appears in front of the actor, and is on render layer 2.
- BG-Scenes should be contained within a single gameobject that we can easily turn into a prefab.
- Inactive BG-scenes should keep their assigned actors in there, so we don't have to keep re-initializing those.

## Acceptance Criteria

This story will be finished when we have a sample unity-scene (known as: scene) which shows at least two separate bg-scenes, and can switch between them using an inky script

**Comment by notexplosive** [comment]
Couple thoughts:
- The dev guide seems like you already have an exact implementation in mind. I'd hope a story would be open-ended "this is the problem that needs to be solved." in this case "Game can switch from one scene to the next" with maybe some explanation about what is a "Scene." Right now the only real constraint is the "SCENE" command in the Narrative Script. How we go about solving that problem is still up to how we choose to engineer this.
- I'm just... kinda confused reading this? Like I don't understand what a bg-scene is. Is that a new term we're using? Why are we calling it that? Is there a better name for it?
- Are we creating a whole new (Unity) Scene for every background transition? (I know we talked about maybe doing that but idk if we reached an agreement). If so, why? Can't we just reuse the existing scene and just change the background image and load a new Narrative Script?

If you (Juice) are planning on taking on this story, then most of what I've above stated doesn't matter. But if you're writing this story for someone else to pick up, I don't think this has the right level of detail.

**Comment by JuiceGrape** [comment]
I don't have an exact implementation in my head, but I do have an exact functionality in my head. It's important it function like that, because all other parts of the system were set up to require it to function like that. If you deviate, shit breaks.

The term bg-scene was coined to differentiate it from a unity scene, like with dialogue script. If you have a better name, feel free to suggest it.

I changes 2 terms in the description which should clear up the functionality of the story. If it still isn't clear after a read or two, hit me up.
