### ISSUE TITLE
Text speeds up when the player keeps the x button held

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#314]
## Description
In the Lua build, when the player continues dialogue, if they keep the button held down the text speeds up after ~2 seconds.

This used to be part of this build but was removed in a PR at some point. Currently the player can speed up text but they must press the x button again after progressing dialogue.

I think it would be good to keep as it's kind of annoying to press the x button multiple times to skip through text.

## Acceptance Criteria

This story will be finished when the player can speed up the text by holding the x button.

**Comment by ViMaSter** [comment]
@PhoebeMitchell Actually wanted to implement it just now and checked out [the Lua build](https://studiolovelies.itch.io/ggjj-lua) - apparently, that's not implemented there either. Do we have a design doc somewhere that mentions this feature?

(I really like it, just don't wanna put in stuff our designers don't actually want in the game.)

**Comment by PhoebeMitchell** [comment]
Just checked the Lua build and confirmed that it _is_ implemented there. Maybe you're confusing this for another feature?

Also why did you assign me? :p

**Comment by ViMaSter** [comment]
Okay, yup, that's fair. I misunderstood this as automatically continuing the dialogue while sped up (essentially a fast-forward) if held for long enough, this actually only talks about speeding up the current dialogue box, my bad, this totally works in the Lua build!

Initially assigned it to me as I started working on it and assigned this back to you since you created the issue and usually are most involved with any of the design stuff. Just wanted to indicate that I was waiting on a response back from you (since only we programmers tend to actively use this repo). Assigning it back to me now, probably going to submit a PR for it in the next few hours.

**Comment by ViMaSter** [comment]
Forgot to properly link this in #331 which implements it; this is present in recent builds!
