### ISSUE TITLE
Support multiple characters on screen at once

### ISSUE THREAD

**Issue by notexplosive** [Studio-Lovelies/GG-JointJustice-Unity#417]
## Description
Writers want the ability to display two characters on screen simultaneously. This is slightly more complex than just "showing 2 characters at once" since we'd need to adjust their positions so they're taking up the left/right of the screen, rather than both sitting centered.

## Acceptance Criteria

This story will be finished when we can achieve an effect similar to shown in this Mockup.

This includes a way for writers to invoke this behavior via a Narrative Script.

![image](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/assets/6920005/338ee6d5-a0e8-41b5-9b6b-542cc4ee9d67)

**Comment by ViMaSter** [comment]
Think it'd be best to chat with art/design on which **exact** scenarios they have in mind for Case 2.

There _are_ a few things that come to mind that might warrant a "new" solution over the existing slot system:
- one slot being occupied by a rotating cast of actors
- a need to dynamically show "between X - Y actors" on screen, rather than a fixed amount

However, if there's only **one** scene with two characters sharing a screen exactly **once**, I'd probably just create a scene with offsets that fits both characters by hand and call it a day. 👀

**Comment by PhoebeMitchell** [comment]
As discussed on discord this is already possible , albeit a bit verbosely as the jump to position action needs to be called as well at the speak action to switch the speaker. A minimum fix might just be to remove the need for jump to position and make the speak action set the speaking animation as well as the text box name/colour. 

Has there been any further communication how the writers/artists want this feature implemented with the new scripts? I.e. is it actually used at all

**Comment by ViMaSter** [comment]
Heeeeeey, guess who created a redundant issue? 🫠

Plenty of usage planned. I'd be fine with closing this in favor of #443, since that has a clear design based on the meeting on August 5th. Or you can just copy over the details to this one and close the new one; whatever you prefer!
