### ISSUE TITLE
Normalize the names of assets in the Resources folder

### ISSUE THREAD

**Issue by notexplosive** [Studio-Lovelies/GG-JointJustice-Unity#47]
## Description

Animations, Sounds, Sprites, etc should all have the same sort of convention that isn't like: `aBoyAndHisBoat`

Possible examples include:
`a-boy-and-his-boat`
`a_boy_and_his_boat`
`A_BOY_AND_HIS_BOAT`

or something. just pick one.

Then we can be more adaptive to user-entered strings in the narrative script.

## Acceptance Criteria

This story will be finished when all the assets have a uniform naming convention, then you can enter some approximately-correct string in the Narrative Script and we get it right "A boy and his boat" should be valid, "a boy And hIs BoAt" should also be valid.

**Comment by JuiceGrape** [comment]
Add a class which takes an input string and shits out a properly formatted string so we can use that. Could do it statically or make an instance of it
Edit: And add it to all instances where it's useful.
So far:

ActorController
AudioController
SceneController (or BGSceneList)

**Comment by ViMaSter** [comment]
@notexplosive Closing this since it wasn't when the PR got merged (think we were [lacking a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)) and from what I can see this Issue is completed. Feel free to reopen, if I've missed anything!
