### ISSUE TITLE
Create wiki

### ISSUE THREAD

**Issue by JuiceGrape** [Studio-Lovelies/GG-JointJustice-Unity#50]
## Description

For the writers to create dialogue scripts, they need a description of what all director actions do. To make this knowledge easy to access, a wiki should be created on this github which contains all the info on how to write dialogue scripts

## Acceptance Criteria

This story will be finished when we have a wiki approved by 2 other people including @Elementalist333 which details all currently implemented director actions, all possible values for these director actions (like actors and evidence), and has a link to the inky documentation

**Comment by Elementalist333** [comment]
approved.

**Comment by ViMaSter** [comment]
This has been moved to [a folder inside the repository](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/tree/develop/docs/methods). Docs are now automatically generated whenever we make changes to the underlying code. (That way docs are always up-to-date if we change, add or remove actions for example.)

For [assets like Evidence and Actors](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/develop/docs/constants.md#evidenceassetname) the description and icon are shown and updated too.

Since it's in `Done - merged into develop` and the main target of this Issue was completed, I'm going to close this. If we ever want to make further improvements or change the layout of the current docs, I think opening up new issues for each change we want to make will make sense.
