### ISSUE TITLE
[BUG] Able to present evidence outside of presenting moments

### ISSUE THREAD

**Issue by JuiceGrape** [Studio-Lovelies/GG-JointJustice-Unity#68]
## Describe the bug

When trying to present evidence, you can do it during any moment in a cross examination, not just during the part where the witness is reciting their testimony.

## Steps To Reproduce

- Open inky test scene
- Play cross examination
- Press the witness
- During the press witness dialogue, press z to open the evidence menu
- Press enter to present the attorney's badge

## Expected behavior

Presenting evidence should be fully disabled when it isn't applicable, so it should only be enabled during cross examination when the witness is reciting their testimony. Every other time, it should simply do nothing (and keep the evidence menu open)

**Comment by JuiceGrape** [comment]
You should also be able to present if you were prompted using the PRESENT_EVIDENCE command

**Comment by ViMaSter** [comment]
The fix we've discussed works and it's covered [by a test](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/c256e7a5416c0004fbf05032a1e65d7cf5f00361/Assets/Tests/PlayModeTests/Scenes/CrossExamination/ViaKeyboard.cs#L60-L103) on the branch (`bugfix/68-present-evidence-outside-of-presenting-moments`) as well.

However, regarding preventing the evidence menu from closing entirely:  
`UnityAction` doesn't seem to support `out` parameters. The only other option would be [System.Func<>](https://docs.microsoft.com/en-us/dotnet/api/system.func-2?view=net-5.0) which would support a return value, but has no support for exposing it via the Unity Editor Inspector-tab.  
That said, even were we to use a `System.Func<>`, we still need support for the ability to hide and show the "[ENTER] -> Present"-part of the controls inside the EvidenceMenu once we add that part of the UI. With a `Systen.Func<>`, we'd only have the ability to see if some event has handled presenting evidence **on enter press**, but no way to check if pressing enter/presenting evidence is an option to begin with.

Instead of only checking for `!_isAtChoice` inside the DialogueController when attempting to present, I'd argue that preventing that event from ever being sent is even better.
I would propose...
- **Adding a `SetCanPresentEvidence(bool canPresent)`-method to `EvidenceMenu`**  
  This would work similar to `SetNavigationButtonsActive()`, except that the value of `canPresent` will determine whether or not presenting evidence is an option right now, instead of `EvidenceMenu` determining it on its own
- **Add `EvidenceMenu.SetCanPresentEvidence(true)` as a subscriber for `DialogueController._onChoicePresented`**  
  That way, every time we're presented with a choice, the EvidenceMenu can show the button mapping to present evidence in the UI + allow the user to actually present evidence
- **Add `EvidenceMenu.SetCanPresentEvidence(false)` as a subscriber for `EvidenceMenu._onEvidenceClicked`**  
  That way, after presenting evidence once, the evidence menu locks itself
- Introduce a `_canPresentEvidence`-field to `EvidenceMenu`
- Set `_canPresentEvidence` to `canPresent` on calls to `EvidenceMenu.SetCanPresentEvidence(bool canPresent)`
- Add an early-out to `EvidenceMenu.OnEvidenceClicked()` if `_canPresentEvidence` set to `false`

@JuiceGrape Any opinions on that solution?  
Also, should I create a PR for the fix now (with the evidence menu still hiding when `Enter` is pressed) or hold off until preventing the menu from closing is implemented too?

**Comment by JuiceGrape** [comment]
@ViMaSter looks good, but a problem here is that onChoicePresented doesn't (or at least shouldn't, idk if it does right now) get called during cross examinations, only during regular dialogue when a choice is encountered.

I suggest going a different route alltogether: Let's add an action to the which switches the dialogue controller into cross examination mode and back when it is neccessary, and then only show the "enter: present" button when we're in cross examination mode, leaving it whenever we're done. 

With this solution, we'd go back to the event which closes the menu when evidence is actually presented, like I proposed before. Seems like the easier solution, because it's something we've been wanting to add anyway.

Edit: Add the fix like we talked about, and I'll make a story for only showing the enter button at the appropriate time after we discuss it with Ana and each other.

**Comment by ViMaSter** [comment]
Just jotting down what we've agreed on inside the Discord:
- Right now the PR allows opening the evidence menu when not inside the "green text loop" of a cross examination. This will continue to be possible.
- However either after pressing or presenting evidence, it's possible to open the window again and close it with the same button used to present evidence.
  - Before this PR, this restarted the "incorrect evidence"-dialogue
  - Right now this PR prevents the dialogue from restarting but closes the window
  - However this PR should already prevent the dialogue from being closed using the 'present'-button at this point

This will be realized by introducing a property to the `EvidenceController`, set by `DialogueController` events, which will prevent `EvidenceMenu.OnEvidenceClicked()` from invoking any further events or closing the window.
This is needed, so we can also update UI visualizations later on, based on whether or not presenting evidence is an option right now.
