### ISSUE TITLE
Player can change the Game Settings

### ISSUE THREAD

**Issue by notexplosive** [Studio-Lovelies/GG-JointJustice-Unity#9]
Blocked by: #8 

## Description

The player should be able to change some core settings from the in game menu.

## Dev Guide

- Make sure we can add new settings or remove old ones easily in the future

## Acceptance Criteria

This story will be finished when the player can:
- Access the game's settings from the main menu and the pause menu
- The settings menu includes: 
  - Volume sliders for Music, SFX, and Voice, which are hooked up and work.
  - A fullscreen toggle (full screen - windowed full screen - windowed)
  - Screen resolution options
  - A brightness slider
  - Controls customization

**Comment by notexplosive** [comment]
Q: Are the settings serialized? AKA: if the player restarts the game, do their settings get preserved?

**Comment by notexplosive** [comment]
This is MASSIVE! I think this would be better served if we have one story that's just the settings menu with one setting. Then other stories to add additional settings.

**Comment by JuiceGrape** [comment]
> This is MASSIVE! I think this would be better served if we have one story that's just the settings menu with one setting. Then other stories to add additional settings.

Disagreed, this should be doable within a single story in unity, and it can be developed fully separately from everything else. We'll keep it like this

**Comment by Elementalist333** [comment]
This is fine as is, as long as we keep a variable number of options settings possible. There has been discussion of multiple languages and other accessibility features, but I want some discussion on how those could be done to see if that's reasonable before committing them to be developed. You all should be a part of that process when we deem it's necessary to decide as we develop, since whatever we decide on you guys will have to make it happen and I don't want to put too much work on things if people aren't excited about them or it implementing it is too... unreasonable.

**Comment by JuiceGrape** [comment]
Good point, added it as a dev guide.
